// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyB5npKPW0pUlDjCgQzi7cugESKzosmhJ_g',
//     appId: '1:1019580031436:web:6a6340cf797b3d230c7d69',
//     messagingSenderId: '1019580031436',
//     projectId: 'myappp-7d129',
//     authDomain: 'myappp-7d129.firebaseapp.com',
//     storageBucket: 'myappp-7d129.firebasestorage.app',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDWMQUJU7VVI6oSoPr7kJTJQBMWNs8vNig',
//     appId: '1:1019580031436:android:fb7240e6bead8ed70c7d69',
//     messagingSenderId: '1019580031436',
//     projectId: 'myappp-7d129',
//     storageBucket: 'myappp-7d129.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAZ1ufi-c0LTlTUwG90LEmsdK0-e1SqJqE',
//     appId: '1:1019580031436:ios:95b83d8e97e317a30c7d69',
//     messagingSenderId: '1019580031436',
//     projectId: 'myappp-7d129',
//     storageBucket: 'myappp-7d129.firebasestorage.app',
//     iosBundleId: 'com.example.newAppMine',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAZ1ufi-c0LTlTUwG90LEmsdK0-e1SqJqE',
//     appId: '1:1019580031436:ios:95b83d8e97e317a30c7d69',
//     messagingSenderId: '1019580031436',
//     projectId: 'myappp-7d129',
//     storageBucket: 'myappp-7d129.firebasestorage.app',
//     iosBundleId: 'com.example.newAppMine',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyB5npKPW0pUlDjCgQzi7cugESKzosmhJ_g',
//     appId: '1:1019580031436:web:5b6ec107cc9008d70c7d69',
//     messagingSenderId: '1019580031436',
//     projectId: 'myappp-7d129',
//     authDomain: 'myappp-7d129.firebaseapp.com',
//     storageBucket: 'myappp-7d129.firebasestorage.app',
//   );
// }
